# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test & lint python

on:
  push:
    branches: [ main, devops/* ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Install poetry
      run: |
        pip install poetry
    - name: Poetry export to requirements.txt
      run: |
        poetry export -f requirements.txt --output requirements.txt --dev
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        poetry install
    - name: Lint with flake8
      run: |
        poetry run bash scripts/lint.sh
    - name: Test with pytest
      run: |
        poetry run bash scripts/test.sh
